kind: pipeline
name: build
type: kubernetes

resources:
  requests:
    memory: 512Mi

steps:
- name: build
  image: golang:1.16-alpine
  pull: always
  commands:
    - apk --no-cache add make
    - make BUILD_CPUS=1

- name: image
  image: plugins/docker
  pull: always
  settings:
    repo: ghcr.io/dravanet/truenas-csi
    registry: ghcr.io
    username: rkojedzinszky
    password:
      from_secret: ghcr.io.password
    auto_tag: true
    auto_label: false
    mirror:
      from_secret: hub_docker_mirror

  privileged: true
  volumes:
    - name: docker
      path: /var/lib/docker

volumes:
  - name: docker
    temp: {}
