kind: pipeline
name: manifest
type: kubernetes

steps:
- image: plugins/manifest
  pull: always
  settings:
    auto_tag: true
    username: rkojedzinszky
    password:
      from_secret: ghcr.io.password

depends_on: []
